gravityring: 0.1.1 
numericmethod: "RungaKutta"
gravitystrength: 0.0001
density: 0.001
definitions:
    mass:
        big: 1000
        small: 10
    distance:
        big: 200
        small: 300
solarsystem:
    solar:
        mass: "mass.big"
        position: "center"
        radius: 20
    planet1:
        mass: "solar.mass * 2"
        position: "solar.position + 10"
    planet2:
        mass: "planet1.mass + 220"
        position: (distance.big + 10, 40)
    planet3:
        mass: "planet2.mass + mass.big"
        postion: "solar.postion.x + 21", "solar.postion.y"

