gravityring: 0.1.1 
numericmethod: "RungaKutta"
gravitystrength: 0.0001
density: 0.001
definitions:
    mass:
        big: 4000
        small: 100
    distance:
        big: 200
        small: 300
solarsystem:
    solar:
        mass: "mass.big"
        position: "center"
        radius: 20
    planet1:
        mass: "solar.mass * 2"
        position: "solar.position + 400"
    planet2:
        mass: "planet1.mass + 223"
        x: "distance.big + 100"
        y: 40 
    planet3:
        mass: "planet2.mass + mass.big"
        x: "solar.x + 44"
        y: "solar.y - 88"

