gravityring: 0.1.1 
numericmethod: "RungaKutta"
gravitystrength: 0.0001
density: 0.001
definitions:
    mass:
        big: 4000
        small: 14
    distance:
        big: 200
        small: 300
system:
    solar:
        mass: "mass.small"
        position: (420, 220)
        radius: 100
        mass: 13
        color: (1,1,0)
    planet1:
        radius: 18
        position: (10, 20)
        velocity_x: 3.0
        velocity_y: 6.0
    planet2:
        radius: 18
        position: (20, 80)
    planet3:
        mass: "planet2.mass + mass.small"
        x: "solar.x + 44"
        y: "solar.y - 88"
    planet4:
        mass: "planet2.mass * 41"
        x: 600
        y: 200
